agent_hyperparameters:
  learning_rate: 0.001
  gamma: 0.99

env_settings:
  savepath: "/home/aaron/f110_gymnasium_ros2_jazzy/rl_training/models" 
  loadpath: "/home/aaron/f110_gymnasium_ros2_jazzy/rl_training/models"                       
  map: '/home/aaron/f110_gymnasium_ros2_jazzy/rl_training/maps/straight_corridor'
  map_ext: '.png'
  start_poses:
    - [0.0, 2.0, 1.5708]   # Ego start pose
    - [1.0, 2.5, 1.5708]   # Opponent start pose


training_settings:
  episodes: 1000
  max_steps: 500
  seed: 42 
