agent_hyperparameters:
  learning_rate: 0.001
  gamma: 0.99

env_settings:
  map: '/home/aaron/f110_gymnasium_ros2_jazzy/rl_training/maps/straight_corridor'
  map_ext: '.png'
  start_poses:
    - [2.0, 2.0, 0.0]   # Ego start pose
    - [1.0, 2.0, 0.0]   # Opponent start pose

training_settings:
  episodes: 1000
  max_steps: 500
